In [1]:
import numpy as np
import sys
import time

In [2]:
arr = np.array([1,2,54,6,6,4,8,56,36])
print(arr)

[ 1  2 54  6  6  4  8 56 36]


In [3]:
type(arr)

numpy.ndarray

In [3]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [4]:
arr1*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [5]:
arr+5

array([ 6,  7, 59, 11, 11,  9, 13, 61, 41])

In [7]:
arr

array([ 1,  2, 54,  6,  6,  4,  8, 56, 36])

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.full((3,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.arange(0,25,8)

array([ 0,  8, 16, 24])

In [6]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [13]:
np.random.randint(2,10,5)

array([4, 5, 2, 3, 5], dtype=int32)

In [17]:
np.random.random((2,2))

array([[0.11293691, 0.88622082],
       [0.05954274, 0.15395386]])

In [18]:
np.std(arr)

np.float64(21.54982741760117)

In [19]:
np.mean(arr)

np.float64(19.22222222222222)

In [20]:
np.min(arr)

np.int64(1)

In [21]:
np.max(arr)

np.int64(56)

In [22]:
np.sqrt(arr)

array([1.        , 1.41421356, 7.34846923, 2.44948974, 2.44948974,
       2.        , 2.82842712, 7.48331477, 6.        ])

In [32]:
# arr = np.array([1,2,3,4,5,6,7,8,9,10])
li = [i for i in range(1,1000000)]
arr = np.array(li)
a = np.array([])
l = []

In [27]:
sys.getsizeof(l)

56

In [33]:
sys.getsizeof(li)
#112


8448728

In [35]:
sys.getsizeof(arr)
#56


8000104

In [39]:
sys.getsizeof(arr)

8104

In [38]:
sys.getsizeof(li)

8448728

In [36]:
list_1 = [i for i in range(10000000)]
list_2 = [i for i in range(10000000)]
list_3 = [0 for i in range(10000000)]
start = time.time()

for i in range(len(list_1)):
    list_3[i] = list_1[i] + list_2[i]
end = time.time()

total = end - start
print(total)

6.709945440292358


In [37]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)
start = time.time()
arr_3 = arr_1 + arr_2
end = time.time()
total = end - start

print(total)

0.09543442726135254
